language: python
# support windows at some point

install:
  - pip install pytest==5.4.2 black==19.10b0 mypy==0.770 flake8==3.8.1

script:
  - pytest

matrix:
  include:
    - name: "Linting and formatting"
      python: 3.6

      script:
      - |
        black --check .
        mypy --ignore-missing-imports .
        flake8 --max-line-length=88 --ignore=E203,W503 .

    - name: "Run tests with Python 3.6"
      python: 3.6
    - name: "Run tests with Python 3.7"
      python: 3.7
    - name: "Run tests with Python 3.8"
      python: 3.8
