language: python
# support windows at some point

install:
  - pip install -e .[test]

script:
  - pytest

matrix:
  include:
    - name: "Linting and formatting"
      python: 3.6
      install:
        - pip install pytest==6.0.2 black==20.8b1 mypy==0.782 flake8==3.8.3
      script:
      - |
        set -eo pipefail
        black --check .
        mypy --ignore-missing-imports .
        flake8 --max-line-length=88 --ignore=E203,W503,E231 .

    - name: "Run tests with Python 3.6"
      python: 3.6
    - name: "Run tests with Python 3.7"
      python: 3.7
    - name: "Run tests with Python 3.8"
      python: 3.8
