name: CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  lint:
    name: Lint and formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Installing dependencies
        run: python3.7 -m pip install black==20.8b1 mypy==0.790 flake8==3.8.4 isort==5.6.4

      - name: Lint using flake8
        run: flake8 .
      - name: Check formatting using black
        run: black --check .
      - name: Check type hinting using mypy
        run: mypy .
      - name: Check import order using isort
        run: isort --check-only .

  test:
    name: Run test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8', '3.9']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -m pip install -e .[test]
      - name: Run tests for Python ${{ matrix.python-version }} using pytest
        run: pytest

  coverage:
    name: Generate coverage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies and pytest-cov
        run: |
          python -m pip install -e .[test]
          python -m pip install pytest-cov
      - name: Run test and generate coverage report
        run: pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          verbose: true
